export const MICROCYCLE = {
  home: {
    label: "HOME WEEK — Loading (PUSH)",
    sub: "Off-swing · full volume · build while fresh · trained engine can absorb it · erg 6am / strength 4pm",
    color: "#00d4ff",
    days: [
      { day:"Sun", am:"Upper Day 1 + optional 20–30min UT2", pm:"—",
        amNote:"Week opener, legs fresh. Upper push/pull — set the week's tone. Optional easy spin after for volume. Mobility block first.",
        amFuel:"Day target ~2,700 cal · 200g protein · ~280g carbs (lightest day). Protein around the lift for the upper work; carbs modest since demand is low.",
        amMeal:{ pre:"FASTED + soy latte (your default). Upper work tolerates fasted easily — no carb load needed for it. The latte's soy protein is a fine touch.", post:"~30g protein + ~30g carbs. Upper sessions are lower glycogen-cost, so post-meal is protein-led. This is where the fuelling lands since you trained fasted." } },
      { day:"Mon", am:"Erg — long (60min UT1)", pm:"—",
        amNote:"Big aerobic anchor. Settle low-130s, sRPE 6. Technique 10s ×3. Watch the force curve. Push = more volume, NOT more intensity.",
        amFuel:"Day target ~3,000 cal · 200g protein · ~350g carbs. Long aerobic = carbs matter. Can row fasted (fat-ox benefit in base), but refuel within 30-60min: ~40-60g carbs + 25-30g protein.",
        amMeal:{ pre:"FASTED + soy latte — ideal for this. Long Z2 fasted is a genuine fat-ox benefit in base; the latte's fine. This is exactly the session to train fasted.", post:"THE meal: ~50-60g carbs + 30g protein within 30-60min. The 60min depletes glycogen — since you rowed fasted, the refuel is where it all lands." } },
      { day:"Tue", am:"Erg — 45min UT1 + rate ladder", pm:"Rest",
        amNote:"Rate ladder mid-session: 2min r20→1min r22→1min r24→30s r26→r20. Same per-stroke feel throughout. Skill, not intensity.",
        amFuel:"Day target ~3,000 cal · 200g protein · ~350g carbs. Don't go fully fasted if pushing the rate work — some carbs in the tank for the ladder. PM rest: eat to recover.",
        amMeal:{ pre:"FASTED + soy latte. The rate ladder is skill not intensity, so fasted is fine — you're not going hard enough to need carbs in the tank. If a rare day you feel flat, a few dates 20min before is plenty.", post:"~40g carbs + 25-30g protein, then eat normally across the day (PM rest)." } },
      { day:"Wed", am:"Erg — 30min UT2 easy", pm:"Lower Day 1",
        amNote:"Genuinely easy (sRPE 3–4) — this is the recovery half of the day. Keep HR under cap. Don't let it bleed into the PM squat's legs.",
        amFuel:"AM of a TWO-A-DAY (day total ~3,200 cal · 200g protein · ~395g carbs). Light fuel before the easy erg, then a proper carb meal after to load for the PM squat.",
        amMeal:{ pre:"FASTED + soy latte — perfect for the easy 30min. It's recovery-easy, no fuel needed.", post:"BIG refuel meal: ~80-100g carbs + 30-40g protein. This is the load-up for the PM squat — most important meal of the day sits here, eaten across the morning ~2hr before lifting (you've broken the fast by now)." },
        pmNote:"Heavy squat — progress the load (real strength age, reps in reserve). Mobility first, breathe through reps. This is the day's priority session.",
        pmFuel:"Fuel BETWEEN sessions: a proper carb meal ~2hr before this squat — don't lift glycogen-depleted. Creatine with the post-AM meal. This is why today eats ~300-400 more than single days.",
        pmMeal:{ pre:"Covered by the post-AM-erg meal (the ~80-100g carb load, eaten ~2hr before this squat). Creatine with it. Small ~20g carb top-up 30min prior if hungry.", post:"~60g carbs + 30-40g protein within 30-60min. Heavy squat = high glycogen cost, refuel properly." } },
      { day:"Thu", am:"Foam roll + Yoga", pm:"Upper Day 2",
        amNote:"Recovery AM — mobility and tissue work, not a session. Sets up the PM upper. Low burn.",
        amFuel:"Day target ~2,900 cal · 200g protein · ~330g carbs. AM is recovery (minimal burn) — normal meals, protein steady.",
        amMeal:{ pre:"No specific pre-meal — mobility isn't a fuelling event. Just eat normally through the morning, protein-forward.", post:"N/A — flows into normal daytime meals." },
        pmNote:"Upper 2 — pull-ups 2nd while fresh, Pallof, forearm-press planks. Mobility first. Won't interfere with Friday's work.",
        pmFuel:"Protein around the lift (muscle). Carbs slightly lower than two-a-day days since only one real session.",
        pmMeal:{ pre:"~400-500 cal · 40-50g carbs · 30-40g protein, ~90min before. Enough to fuel the pulls, not heavy.", post:"~30-40g protein + ~30g carbs. Protein-led — upper work's glycogen cost is modest." } },
      { day:"Fri", am:"Erg — 45min UT1", pm:"Lower Day 2",
        amNote:"Z2 aerobic AM. Steady, controlled. Fortnight video self-review: film 2min side-on. Mobility first.",
        amFuel:"AM of a TWO-A-DAY (day total ~3,200 cal · 200g protein · ~395g carbs). Refuel after the erg to load for the PM lower.",
        amMeal:{ pre:"FASTED + soy latte — steady 45min aerobic, ideal fasted.", post:"BIG refuel: ~80-100g carbs + 30-40g protein. Loads up for the PM lower — eaten across the day, ~2hr before lifting." },
        pmNote:"RDL rehab + power PM (6hr gap from erg). The hamstring/glute rehab work — quality over load. Protect the movement.",
        pmFuel:"Carb meal ~2hr before — protect the RDL/power work with glycogen. Don't lift the rehab session under-fuelled (form matters most here).",
        pmMeal:{ pre:"The post-AM-erg carb load (~80-100g carbs) doubles as this pre-meal, ~2hr before. Rehab form needs fuel — don't skimp. Small carb top-up 30min prior if needed.", post:"~50-60g carbs + 30-40g protein within 30-60min." } },
      { day:"Sat", am:"Erg — long (60–70min UT1)", pm:"—",
        amNote:"Extended long row — push the DURATION this week (engine can take it). Genuinely easy pace, sRPE 5–6. Erg only, no strength.",
        amFuel:"Peak-volume day · ~3,200 cal · 200g protein · ~395g carbs. Longest row = highest glycogen demand. Hydrate hard (replace ~150% of fluid lost). Refuel within 30-60min after.",
        amMeal:{ pre:"FASTED + soy latte is your default. ONE honest caveat: the 60-70min long row is the session where fasted is most likely to leave you flat late in the row. If you fade past ~45min, ~30g carbs during (sports drink/gel) helps — not a pre-meal, just mid-row fuel. Otherwise fasted is fine.", post:"THE big one: ~60-80g carbs + 30g protein within 30-60min. Highest glycogen cost of the week + you trained fasted = refuel properly. Rehydrate to 150% of fluid lost." } },
    ],
  },
  fifo: {
    label: "FIFO WEEK — Consolidation (RECOVER)",
    sub: "On-swing · 12hr shifts · the deload that banks last week's gains · sleep is king",
    color: "#ffd700",
    machineNote: "Camp uses Technogym (Concept2 harder to access). For FIFO maintenance rows that's fine — connect Technogym app → Strava so sessions auto-capture. Log as HR/sRPE-anchored cross-training, NOT on the Concept2 watts trend or HR130 barometer (brand power numbers aren't comparable). Row to HR130 + report sRPE — those transfer across machines, watts don't. Comparable data resumes on the home Concept2. BUILDING a personal conversion (see below) to eventually give real Technogym watt targets.",
    days: [
      { day:"Sun", am:"Travel + foam roll/yoga if energy", pm:"—",
        amNote:"Transition day. Last week's load consolidates now. Sleep priority — the swing compresses it.",
        amFuel:"Recovery week, lower demand. ~2,600-2,800 cal · 200g protein (HOLD — protects muscle during the deload) · ~250g carbs. Travel: protein + whole foods over airport carbs.",
        amMeal:{ pre:"No training meal needed (travel/mobility day). Eat normally — protein-forward, whole foods over airport carbs.", post:"N/A — normal daytime meals, protein floor held." } },
      { day:"Mon", am:"Erg 30min easy (pre/post shift)", pm:"—",
        amNote:"Z2 only. The 12hr shift IS the stress — the erg is just engine maintenance. Adaptation from last week happens THIS week; don't fight the deload.",
        amFuel:"~2,700 cal · 200g protein · ~280g carbs. Fuel for the shift's demands, not the row. Pack protein-forward meals. Hydrate (shift work dehydrates).",
        amMeal:{ pre:"Minimal for the easy 30min — a banana/coffee if anything. The shift's the real fuelling challenge: pack protein-forward meals for the 12hr.", post:"~30g protein + light carbs. Then fuel across the shift, hydrate well." } },
      { day:"Tue", am:"Rest or Erg 20min", pm:"—",
        amNote:"Optional. Skip entirely if the shift was heavy or sleep was poor. No guilt — recovery is the week's job.",
        amFuel:"~2,600 cal · 200g protein · ~250g carbs. Minimal training — eat to recover, not to fuel. Protein floor holds.",
        amMeal:{ pre:"No pre-meal — optional 20min easy at most. Eat to recover, not to fuel.", post:"Normal meals, protein floor (200g) holds. Carbs modest." } },
      { day:"Wed", am:"Erg 30min easy", pm:"—",
        amNote:"Aerobic touch, zero intensity. Keep the engine ticking without adding fatigue.",
        amFuel:"~2,700 cal · 200g protein · ~280g carbs. Light aerobic only. Sleep + recovery are the real priority.",
        amMeal:{ pre:"Minimal — easy 30min, fasted is fine. Banana if hungry.", post:"~25-30g protein + light carbs. Recovery-week eating, nothing special needed." } },
      { day:"Thu", am:"Foam roll + Yoga, or Prehab+Shoulder if energy", pm:"—",
        amNote:"Recovery or light band prehab (travel-friendly). Keeps the shoulder/asymmetry work ticking without load.",
        amFuel:"~2,600 cal · 200g protein · ~250g carbs. Recovery day — nutrient density over volume.",
        amMeal:{ pre:"No training meal — mobility/prehab isn't a fuelling event. Normal protein-forward eating.", post:"N/A — flows into recovery-week meals, nutrient density over volume." } },
      { day:"Fri", am:"Erg 30min easy", pm:"—",
        amNote:"Engine ticking over. Easy aerobic, no more.",
        amFuel:"~2,700 cal · 200g protein · ~280g carbs. Standard recovery-week fuelling.",
        amMeal:{ pre:"Minimal — easy 30min, fasted fine.", post:"~25-30g protein + light carbs. Standard recovery-week intake." } },
      { day:"Sat", am:"Rest or Erg 20–30min", pm:"—",
        amNote:"Auto-regulate to how the swing went. Home loading resumes tomorrow — arrive recovered, not depleted.",
        amFuel:"~2,700 cal · 200g protein · ~290g carbs. Slight carb bump to refuel glycogen ahead of the PUSH week starting tomorrow.",
        amMeal:{ pre:"Minimal — optional easy session. ", post:"Slightly higher carbs across the day (~290g) to top up glycogen before home loading resumes tomorrow. Protein floor holds." } },
    ],
  },
};

export const SEASON = {
  current: 1,
  label: "SEASON 1",
  span: "Jun 2026 – Mar 2027",
  finale: "World Rowing Virtual Indoor Champs (late Feb 2027)",
  arc: "Base (Jun–Aug) → Build 1 (Sep–Oct) → Build 2 (Nov–Dec) → Peak (Jan–Feb) → Race → Recover (Mar)",
  goal: "First full competitive season. Establish the baseline across all 3 formats (1-min/1000m/5000m). Lean out through base, build power through Build, peak for Worlds.",
  next: "Season 2 (Apr 2027+) rebuilds off a higher floor — more volume, the lessons of S1 banked, a stronger base each cycle. The multi-year arc = stacked seasons.",
  principle: "A season is the unit of progression. Worlds is the finale, not the finish. Each season: full cycle, race the finale, recover, then begin again higher.",
};

export const SEASON_2 = {
  label: "SEASON 2",
  span: "Apr 2027 – Mar 2028",
  theme: "Off a higher floor. Introduce the 2000m (the classic indoor distance) — opens the door to in-person racing. First live-race experience the big step.",
  fork: "STRATEGIC FORK: keep the virtual Worlds as finale (familiar, proven), OR step up to an in-person event (CRASH-B / Aus Indoor Champs / in-person WRICH). In-person = the serious-competitor leap but needs 2k/500m focus. Decide early in S2 — it shapes the whole format emphasis.",
  phases: [
    { phase:"Transition · Apr 27", events:"Recover from S1. Reflect on Worlds. Plan S2 + make the in-person fork decision.", kind:"recover" },
    { phase:"Base 2 · May–Aug 27", events:"Higher-floor base (6-7h). On-water option in WA winter. Benchmarks: CP retest, 5k TT off a stronger engine. Possibly introduce 2k baseline if going in-person.", kind:"benchmark" },
    { phase:"Build 1 · Sep–Oct 27", events:"Erg Power Series again (if recurring) — now stronger, target a podium. Power/sprint focus.", kind:"competition" },
    { phase:"Build 2 · Nov–Dec 27", events:"Monthly challenges. 🌟 FIRST IN-PERSON COMP — a regional/state Australian indoor race (less travel than overseas, ideal first live-race experience).", kind:"aspirational" },
    { phase:"Peak · Jan–Feb 28", events:"2k tests + race-pace tune-ups. 🌟 CRASH-B SPRINTS (Boston, ~late Feb/Mar) — the bucket-list indoor champs, 2000m, the global aspirational target. Big trip from WA — investigate cost/timing early.", kind:"aspirational" },
    { phase:"Race · Feb–Mar 28", events:"Season finale: virtual Worlds (Feb 2028) AND/OR the chosen in-person event. 🌟 In-person WRICH (2000m/500m) if it materialises.", kind:"TARGET" },
    { phase:"Post · Mar 28", events:"WR Virtual Sprints (1000m) season-closer. Recover. Open Season 3 off a higher floor again.", kind:"optional" },
  ],
  aspirational: [
    { name:"CRASH-B Sprints (Boston)", what:"The world's most famous indoor champs. 2000m. Every Feb/Mar. The bucket-list travel race — huge trip from WA, but THE indoor rowing event. A genuine serious-competitor milestone.", chase:"Investigate 2028 dates + cost early. A real goal to build toward." },
    { name:"Australian Indoor Champs / state comps", what:"Domestic in-person racing — far less travel for a WA athlete. The sensible FIRST live-race experience before chasing overseas events.", chase:"Find the WA/national indoor calendar. Lowest barrier to first in-person race." },
    { name:"In-person WRICH (2000m/500m)", what:"World Rowing's planned in-person championship (traditional distances). If it runs, the natural in-person step-up from the virtual Worlds.", chase:"Watch for World Rowing's announcement." },
    { name:"HYROX (erg + fitness crossover)", what:"Functional-fitness race featuring the erg. A fun, different challenge — tests fitness beyond pure rowing.", chase:"Optional/fun. Investigate if cross-training appeals." },
  ],
};

export const EVENT_LADDER = [
  { date:"Wed 1 Jul 26", name:"CP Test #1 (4-min)", kind:"benchmark", phase:"Base",
    serves:"Keystone pt 1 — first clean rowing-test anchor on fresh legs (post-FIFO taper). 4-min all-out (C2 protocol, pace-able, on the ranking). Sets a trustworthy threshold anchor; CP+W′ model completed by test #2 next home week. Unlocks %CP pacing + Power Guide." },
  { date:"~Mid Jul 26", name:"CP Test #2 (2nd duration)", kind:"benchmark", phase:"Base",
    serves:"Keystone pt 2 — second maximal effort at a different duration (e.g. 1-min + the 4-min, or a longer 7-10min piece) to complete the 2-point power-duration model. More reliable than any single all-out test. Builds CP + W′ properly." },
  { date:"~Early Aug 26", name:"5k Time Trial", kind:"benchmark", phase:"Base end",
    serves:"First real read on the 5000m format + what base built. Do fresh, low-stakes." },
  { date:"12 Sep–9 Oct 26", name:"Erg Power Series", kind:"competition", phase:"Build 1",
    serves:"FIRST competition. Tests 1-min/1000m power end (2 of 3 Worlds formats). Heavyweight advantage. Sharpen 2-3wk prior." },
  { date:"Nov–Dec 26", name:"C2 Monthly / handicap race", kind:"competition", phase:"Build 2",
    serves:"Low-stakes competitive volume — race within training, no peak needed. Keeps the edge through the build." },
  { date:"~Mid Jan 27", name:"2k Test", kind:"benchmark", phase:"Peak lead-in",
    serves:"Universal rowing benchmark — best single fitness measure, predicts across all distances. Pre-peak data." },
  { date:"Late Jan 27", name:"1000m + 1-min tune-ups", kind:"benchmark", phase:"Peak",
    serves:"Race-specific rehearsals at Worlds distances, ~3-4wk out. Dial pacing, not compete." },
  { date:"🎯 Late Feb 27", name:"World Rowing Virtual Indoor Champs", kind:"TARGET", phase:"Race",
    serves:"THE GOAL. 1-min, 1000m, 5000m. Two Feb weekends (2026 pattern: Feb 21/22 + 28). The only true peak." },
  { date:"Early Mar 27", name:"WR Virtual Indoor Sprints (1000m)", kind:"optional", phase:"Post-peak",
    serves:"Recurs every March, race anywhere. Bonus 1000m while still sharp — clean season-closer before recovery." },
];

export const PHASE_CONTEXT = {
  current: "BASE",
  phaseLabel: "Phase 1 — Base (Extended)",
  window: "Jun–Aug 2026",
  weeksIn: 3,
  weeksTotal: 12,
  doing: "Building the aerobic engine. All erg in UT1/UT2, volume rising ~10%/wk, no intensity. Strength progressing on compounds.",
  why: "Peripheral adaptations (mitochondria, capillaries, fat oxidation) take 6–8wk minimum and can't be rushed. The foundation everything later is built on.",
  notYet: "No threshold or VO2 work — that's Build 1 (Sept+). Resisting intensity now IS the work.",
  nextGate: "End-of-base 5k benchmark (~wk 6, early Aug) — first real fitness checkpoint.",
  arc: [
    { phase:"BASE",     window:"Jun–Aug",       active:true  },
    { phase:"BUILD 1",  window:"Sep–Oct",       active:false },
    { phase:"BUILD 2",  window:"Nov–Dec",       active:false },
    { phase:"PEAK",     window:"Jan–Feb",       active:false },
    { phase:"RACE",     window:"late Feb 2027", active:false },
  ],
};

export const ROSTER_ANCHOR = new Date(2026, 5, 23);

export const SESSION_OVERRIDES = {
  "2026-07-01": {
    day:"Wed", override:true,
    am:"🎯 CP TEST #1 — 4-min all-out",
    pm:"—",
    amNote:"KEYSTONE TEST (fresh legs, post-FIFO taper — the whole point of waiting). PROTOCOL: thorough warm-up (15-20min building, 3×10-15s bursts to open up, full recovery before starting), then 4 MINUTES ALL-OUT at fixed drag 125. PACING — this is the trap: don't fire off at cycling-FTP instinct. Target a HARD-but-holdable opening (think ~105-108% of your est. CP ~190W, so ~200-205W) and hold/build — a mispaced fade ruins the number. Better to finish with a tiny bit left than blow up at 2:30. Average power over the full 4min is the headline; we'll also note the last-30s power. Log to C2 ranking. WHY 4-min not 3MT: pace-able for a first rowing test (the 3MT's all-out-from-gun is hard to pace blind + only moderately reliable in trained rowers). This is anchor #1 — test #2 next home week completes the CP+W′ model. READINESS GATE: if you arrive home flat from a rough swing, push it a day. Test fresh or don't test.",
    amFuel:"Fuel this one PROPERLY — it's a maximal effort, not a fasted base row. Day target ~3,000 cal · 200g protein · ~350g carbs. The test is the exception to the fasted-AM default.",
    meal:{ pre:"EXCEPTION to fasted-AM — a max test wants fuel. ~40-60g fast carbs 60-90min before (oats/banana/toast), low fat, plus the latte. Carbohydrate-replete + hydrated = the test conditions the research uses. Don't test fasted; you'll under-read.", post:"~60g carbs + 30-40g protein within 30-60min. Hard effort = real glycogen cost." },
  },
  "2026-06-19": {
    day:"Fri", override:true,
    am:"Combined Strength — Lower 2 (RDL-led) → Upper 1",
    pm:"—",
    amNote:"ONE-OFF SWAP (heavy rowing week — 6 straight days on the erg). The 45min UT1 is swapped for Upper 1, combined with Lower 2 as one large session. Breaks the consecutive-rowing chain, redistributes load to a different system without cutting work. SEQUENCE (order matters): (1) Mobility prep first — glute activation, the rehab area follows. (2) LOWER 2 FIRST while fresh — RDL rehab + power. This is the priority + the most form-demanding; do it before fatigue degrades control. Don't grind it tired. (3) UPPER 1 second — press, pull, accessories; upper absorbs being second fine. WATCH: it'll run 75-90+min. If form or focus fades in the back half, cut accessories — trim, don't grind junk volume. Morning readiness check first: legs may still carry Wed's squat (Lower 1 was 6/17) — if the posterior chain is cooked, the rehab RDLs are the thing to protect, so reduce load or split.",
    amFuel:"Big combined-strength day. Day target ~3,200 cal · 200g protein · ~395g carbs (treat like a two-a-day — it is one, just stacked). Fuel properly BEFORE: carb meal ~2hr prior so the RDLs aren't done glycogen-depleted (rehab form needs fuel). Protein around the session. Creatine with a meal. Refuel within 30-60min after — this is a long block.",
    meal:{ pre:"FASTED is your default — just the soy latte is fine (the few g of soy protein won't hurt). HONEST CALL for a heavy AM lift: the RDLs are better with some fuel, BUT if you train fasted reliably and feel strong, do that — don't force a meal you won't eat. Compromise if you want it: ~30-40g fast carbs 20-30min before (banana, a few dates, or carbs in the latte) — small, just tops the tank for the rehab work without sitting heavy. Skip if fasted feels fine.", post:"THE meal that matters for you. ~60-80g carbs + 40g protein within 30-60min. This is where the day's fuelling lands — you trained fasted, so refuel properly after the long block." },
  },
};

export const DEFICIT_PROGRAM = {
  trigger: "Start ONLY after TDEE confirmed (clean week + stable weight). Not before — a deficit off a wrong maintenance does nothing or cuts too hard.",
  rate: "~0.25–0.3kg/week (avg ~230–350 cal/day under ~3,030 maintenance)",
  days: [
    { day:"Mon", train:"60min UT1",       cal:2800, p:210, c:300, f:84, cut:"-200" },
    { day:"Tue", train:"45min + ladder",  cal:2800, p:210, c:300, f:84, cut:"-200" },
    { day:"Wed", train:"UT2 + Lower",     cal:3100, p:210, c:375, f:87, cut:"-100 (protect lift)" },
    { day:"Thu", train:"yoga + Upper",    cal:2500, p:210, c:250, f:80, cut:"-400 (light day)" },
    { day:"Fri", train:"45min + Lower",   cal:3100, p:210, c:375, f:87, cut:"-100 (protect lift)" },
    { day:"Sat", train:"long row",        cal:3000, p:210, c:350, f:84, cut:"-200" },
    { day:"Sun", train:"rest",            cal:2300, p:210, c:210, f:78, cut:"-400 (rest day)" },
  ],
  guardrails: [
    "POWER@HR130 BAROMETER = the early-warning. ~150W now. Holds/climbs → fat off, fitness intact, continue. Drops 2 sessions running → add ~200 cal back.",
    "Fasted-AM weight should fall ~0.25–0.4kg/wk. Faster = too aggressive, ease up.",
    "HRV/sleep degrading → under-fuelling, back off.",
    "Squat/lift numbers dropping → deficit too steep.",
    "Protein 200–220g (HIGHER in deficit — muscle-sparing + satiety). Fat ≥75g (hormones). Cut CARBS on easy days, not protein or fat.",
  ],
  phase: "Run through BASE (now–Aug, forgiving of deficit). PAUSE at Build-1 (Sept) intensity ramp — eat maintenance to fuel hard work. Resume later if needed.",
  note: "Erg advantage: hold absolute watts while dropping fat = better power-to-weight = effectively faster splits. 'Hold the watts' is the whole game.",
};

export const FUELLING = {
  byType: [
    { type:"Fasted easy row (UT1/UT2)", color:"#00d4ff",
      guide:"KEEP fasted — at HR130 you burn mostly fat; fasted enhances fat-ox adaptation, exactly what base wants. If ever flat: banana / few dates 20min before. >75min: sip carbs during." },
    { type:"Two-a-day (erg AM + lift PM)", color:"#f472b6",
      guide:"THE priority. Fasted row fine. THEN: refuel within 30–60min post-row (40–60g carb + 25–30g protein) to restock glycogen. Eat properly ACROSS the day — don't coast on light meals till 4pm (that's the energy leak). Pre-lift 2–3pm: real carb meal/snack so you can load the squat." },
    { type:"Strength day", color:"#34d399",
      guide:"Glycogen-dependent — unlike easy rowing. Arrive fuelled: carbs in the 2–3 hrs before. Protein 25–40g post. Don't lift depleted." },
    { type:"Hard intervals (Build phase)", color:"#ff6b35",
      guide:"FUEL these (unlike easy work): carbs 1–2hr before, carbs during if >45min work. Dial when Build arrives." },
  ],
  hydration: [
    "Loss ~1kg (1L) per hour rowing — confirmed 6/15 (95.7→94.7 post-row). WA heat amplifies it.",
    "Pre-row: 500ml on waking before a fasted session.",
    "Post: replace 150% of loss — ~1.5L after a 1kg-loss row. Weigh before/after to know the real number.",
    "Electrolytes not just water — sodium especially, on two-a-days + heat. Plain water without salt just gets peed out.",
    "PM lift in heat: arrive already hydrated from the day, don't try to catch up at 4pm.",
  ],
  protein: "Floor 188g/day non-negotiable — protects muscle through any deficit. Spread across meals (~30–40g/meal), not back-loaded.",
};

export const NUTRITION_PRINCIPLES = [
  ["🎯","Conservative deficit only: 0.25–0.4 kg/week. Aggressive cuts tank session quality and cost muscle. Slow loss preserves both."],
  ["📊","Deficit is a weekly average, not a daily rule. Eat more around hard training, less on rest days — easier to sustain, better for performance."],
  ["🔋","Two-a-day days need ~300–400 extra calories vs single-session days. Don't run a deficit on your highest-output days."],
  ["⏱️","Peri-workout: 40–60g carbs + 25–30g protein within 30min of the AM erg on two-a-day days. Refuels for the PM strength session."],
  ["📱","Consistency > precision. Log immediately, not end-of-day from memory. The logging habit is the lever — nail protein, roughly land calories, the rest sorts itself."],
  ["⚡","Performance guardrail: if watts at a given HR start dropping, ease the deficit. For 2k erg, absolute power matters more than bodyweight — protect the power numbers."],
];

export const TECHNOGYM_CONVERSION = {
  status: "Auto-collecting from Strava — both Concept2 and Technogym sessions flow in. 0 Technogym points so far (none rowed yet).",
  method: "AUTOMATIC: Technogym (via mywellness→Strava) and Concept2 sessions both land in Strava. I pull HR + displayed watts from each via the connector. Pair Technogym HR130 rows against Concept2 HR130 power → derive the offset. No manual reporting needed — just row to HR130 at camp and it self-captures.",
  current_c2_anchor: "HR130 ≈ 150W (Concept2, 6/13)",
  pairs: [],
  caveats: "Strava may carry Technogym's displayed watts (good) or only HR/pace (then HR-anchor only). Check first session's data richness. Re-check offset periodically — Concept2 HR130 baseline is climbing. Need ~4–6 clean points; offset may differ at high vs low power.",
};

export const DAILY_ROUTINE = {
  trigger: "On 'what's today's schedule' / 'today's plan' / daily check-in",
  steps: [
    "1. Strava list_activities (last 2–3 days, NOT today-only — Strava timestamps run ~1 day off due to TZ/sync, so date-filtering today misses sessions). Match by distance/duration, not timestamp.",
    "2. For each new erg/bike session: get_activity_performance — HR, watts, cadence, relative effort",
    "3. Log new sessions to dashboard (Concept2 links still preferred for erg DETAIL — Strava catches what wasn't sent + Technogym/cycling)",
    "4. Flag any Technogym HR130 rows → feed the conversion model",
    "5. THEN give today's schedule from the microcycle, adjusted for what's already done + recovery state",
  ],
  note: "Strava is the safety net — nothing trains without being captured. Concept2 share links still sent for force-curve/split detail on key erg sessions. This routine keeps the schedule answer current, not stale.",
};
